// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function ConnectDevices(arg1:menu.CallbackData):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OpenAbout(arg1:menu.CallbackData):Promise<void>;

export function OpenDevices(arg1:menu.CallbackData):Promise<void>;

export function OpenHome(arg1:menu.CallbackData):Promise<void>;

export function OpenMonitor(arg1:menu.CallbackData):Promise<void>;

export function OpenNewWindow():Promise<void>;

export function WindowReload():Promise<void>;
