// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDevices(arg1) {
  return window['go']['main']['App']['ConnectDevices'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenAbout(arg1) {
  return window['go']['main']['App']['OpenAbout'](arg1);
}

export function OpenDevices(arg1) {
  return window['go']['main']['App']['OpenDevices'](arg1);
}

export function OpenHome(arg1) {
  return window['go']['main']['App']['OpenHome'](arg1);
}

export function OpenMonitor(arg1) {
  return window['go']['main']['App']['OpenMonitor'](arg1);
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function WindowReload() {
  return window['go']['main']['App']['WindowReload']();
}
