// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Device']['AddDevice'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['Device']['DeleteDevice'](arg1);
}

export function GetDevices() {
  return window['go']['main']['Device']['GetDevices']();
}
