// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMonitor(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21) {
  return window['go']['main']['Monitor']['AddMonitor'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21);
}

export function DeleteMonitor(arg1) {
  return window['go']['main']['Monitor']['DeleteMonitor'](arg1);
}

export function GetMonitors() {
  return window['go']['main']['Monitor']['GetMonitors']();
}

export function GetSingleMonitorForEdit(arg1) {
  return window['go']['main']['Monitor']['GetSingleMonitorForEdit'](arg1);
}

export function OpenCSVFile(arg1) {
  return window['go']['main']['Monitor']['OpenCSVFile'](arg1);
}

export function StartAllMonitoring() {
  return window['go']['main']['Monitor']['StartAllMonitoring']();
}

export function StartSingleMonitoring(arg1) {
  return window['go']['main']['Monitor']['StartSingleMonitoring'](arg1);
}

export function StopAllMonitoring() {
  return window['go']['main']['Monitor']['StopAllMonitoring']();
}

export function StopSingleMonitoring(arg1) {
  return window['go']['main']['Monitor']['StopSingleMonitoring'](arg1);
}

export function UpdateMonitor(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22) {
  return window['go']['main']['Monitor']['UpdateMonitor'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22);
}
