// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMonitor(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:number,arg6:number,arg7:string,arg8:boolean,arg9:boolean,arg10:boolean,arg11:number,arg12:string,arg13:number,arg14:string,arg15:number,arg16:string,arg17:string,arg18:boolean,arg19:boolean,arg20:boolean,arg21:boolean):Promise<void>;

export function DeleteMonitor(arg1:string):Promise<void>;

export function GetMonitors():Promise<Array<main.Monitor>>;

export function GetSingleMonitorForEdit(arg1:string):Promise<main.Monitor>;

export function OpenCSVFile(arg1:string):Promise<void>;

export function StartAllMonitoring():Promise<void>;

export function StartSingleMonitoring(arg1:string):Promise<void>;

export function StopAllMonitoring():Promise<void>;

export function StopSingleMonitoring(arg1:string):Promise<void>;

export function UpdateMonitor(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number,arg6:number,arg7:number,arg8:string,arg9:boolean,arg10:boolean,arg11:boolean,arg12:number,arg13:string,arg14:number,arg15:string,arg16:number,arg17:string,arg18:string,arg19:boolean,arg20:boolean,arg21:boolean,arg22:boolean):Promise<void>;
